import './globals.css';
import { Inter } from 'next/font/google';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'test',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <Providers>
      <body className={inter.className} suppressHydrationWarning>
        {children}
      </body>
    </Providers>
  </html>
);

export default RootLayout;
